### ISSUE TITLE
i dont have a api key

### ISSUE THREAD

**Issue by brickyosu** [omkelderman/osu-replay-downloader#7]
i can get one but i am too young for that because i am under 12... i want osu replay downloader for danser knockout mode except the thing blocking me is api keys. can you try making a non api version or just figure something out about it? :(

**Comment by omkelderman** [comment]
this is a piece of software dedicated to downloading data from osu servers, the only reliable way to do that is with an api key. There will not be a version (at least from me) that supports fetching data without it, sorry.
